/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntrepriseRouteImport } from './routes/entreprise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrepriseIndexRouteImport } from './routes/entreprise.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EntrepriseStatistiquesRouteImport } from './routes/entreprise.statistiques'
import { Route as EntrepriseRetardsRouteImport } from './routes/entreprise.retards'
import { Route as EntrepriseProfilRouteImport } from './routes/entreprise.profil'
import { Route as EntrepriseOperationsRouteImport } from './routes/entreprise.operations'
import { Route as EntrepriseMotDePasseRouteImport } from './routes/entreprise.mot-de-passe'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminLivraisonsRouteImport } from './routes/admin.livraisons'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as EntrepriseLivreursIndexRouteImport } from './routes/entreprise.livreurs.index'
import { Route as EntrepriseLivraisonsIndexRouteImport } from './routes/entreprise.livraisons.index'
import { Route as AdminTransporteursIndexRouteImport } from './routes/admin.transporteurs.index'
import { Route as AdminMarchandsIndexRouteImport } from './routes/admin.marchands.index'
import { Route as AdminComptesIndexRouteImport } from './routes/admin.comptes.index'
import { Route as AdminCommandesIndexRouteImport } from './routes/admin.commandes.index'
import { Route as EntrepriseLivreursNouveauRouteImport } from './routes/entreprise.livreurs.nouveau'
import { Route as AdminTransporteursNouveauRouteImport } from './routes/admin.transporteurs.nouveau'
import { Route as AdminTransporteursIdRouteImport } from './routes/admin.transporteurs.$id'
import { Route as AdminMarchandsIdRouteImport } from './routes/admin.marchands.$id'
import { Route as AdminCommandesIdRouteImport } from './routes/admin.commandes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseRoute = EntrepriseRouteImport.update({
  id: '/entreprise',
  path: '/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrepriseIndexRoute = EntrepriseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntrepriseRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EntrepriseStatistiquesRoute = EntrepriseStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => EntrepriseRoute,
} as any)
const EntrepriseRetardsRoute = EntrepriseRetardsRouteImport.update({
  id: '/retards',
  path: '/retards',
  getParentRoute: () => EntrepriseRoute,
} as any)
const EntrepriseProfilRoute = EntrepriseProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => EntrepriseRoute,
} as any)
const EntrepriseOperationsRoute = EntrepriseOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => EntrepriseRoute,
} as any)
const EntrepriseMotDePasseRoute = EntrepriseMotDePasseRouteImport.update({
  id: '/mot-de-passe',
  path: '/mot-de-passe',
  getParentRoute: () => EntrepriseRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLivraisonsRoute = AdminLivraisonsRouteImport.update({
  id: '/livraisons',
  path: '/livraisons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const EntrepriseLivreursIndexRoute = EntrepriseLivreursIndexRouteImport.update({
  id: '/livreurs/',
  path: '/livreurs/',
  getParentRoute: () => EntrepriseRoute,
} as any)
const EntrepriseLivraisonsIndexRoute =
  EntrepriseLivraisonsIndexRouteImport.update({
    id: '/livraisons/',
    path: '/livraisons/',
    getParentRoute: () => EntrepriseRoute,
  } as any)
const AdminTransporteursIndexRoute = AdminTransporteursIndexRouteImport.update({
  id: '/transporteurs/',
  path: '/transporteurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarchandsIndexRoute = AdminMarchandsIndexRouteImport.update({
  id: '/marchands/',
  path: '/marchands/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComptesIndexRoute = AdminComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesIndexRoute = AdminCommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => AdminRoute,
} as any)
const EntrepriseLivreursNouveauRoute =
  EntrepriseLivreursNouveauRouteImport.update({
    id: '/livreurs/nouveau',
    path: '/livreurs/nouveau',
    getParentRoute: () => EntrepriseRoute,
  } as any)
const AdminTransporteursNouveauRoute =
  AdminTransporteursNouveauRouteImport.update({
    id: '/transporteurs/nouveau',
    path: '/transporteurs/nouveau',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTransporteursIdRoute = AdminTransporteursIdRouteImport.update({
  id: '/transporteurs/$id',
  path: '/transporteurs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarchandsIdRoute = AdminMarchandsIdRouteImport.update({
  id: '/marchands/$id',
  path: '/marchands/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesIdRoute = AdminCommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entreprise': typeof EntrepriseRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/entreprise/mot-de-passe': typeof EntrepriseMotDePasseRoute
  '/entreprise/operations': typeof EntrepriseOperationsRoute
  '/entreprise/profil': typeof EntrepriseProfilRoute
  '/entreprise/retards': typeof EntrepriseRetardsRoute
  '/entreprise/statistiques': typeof EntrepriseStatistiquesRoute
  '/admin/': typeof AdminIndexRoute
  '/entreprise/': typeof EntrepriseIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/transporteurs/nouveau': typeof AdminTransporteursNouveauRoute
  '/entreprise/livreurs/nouveau': typeof EntrepriseLivreursNouveauRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/marchands/': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs/': typeof AdminTransporteursIndexRoute
  '/entreprise/livraisons/': typeof EntrepriseLivraisonsIndexRoute
  '/entreprise/livreurs/': typeof EntrepriseLivreursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/entreprise/mot-de-passe': typeof EntrepriseMotDePasseRoute
  '/entreprise/operations': typeof EntrepriseOperationsRoute
  '/entreprise/profil': typeof EntrepriseProfilRoute
  '/entreprise/retards': typeof EntrepriseRetardsRoute
  '/entreprise/statistiques': typeof EntrepriseStatistiquesRoute
  '/admin': typeof AdminIndexRoute
  '/entreprise': typeof EntrepriseIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/transporteurs/nouveau': typeof AdminTransporteursNouveauRoute
  '/entreprise/livreurs/nouveau': typeof EntrepriseLivreursNouveauRoute
  '/admin/commandes': typeof AdminCommandesIndexRoute
  '/admin/comptes': typeof AdminComptesIndexRoute
  '/admin/marchands': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs': typeof AdminTransporteursIndexRoute
  '/entreprise/livraisons': typeof EntrepriseLivraisonsIndexRoute
  '/entreprise/livreurs': typeof EntrepriseLivreursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/entreprise': typeof EntrepriseRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/livraisons': typeof AdminLivraisonsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/entreprise/mot-de-passe': typeof EntrepriseMotDePasseRoute
  '/entreprise/operations': typeof EntrepriseOperationsRoute
  '/entreprise/profil': typeof EntrepriseProfilRoute
  '/entreprise/retards': typeof EntrepriseRetardsRoute
  '/entreprise/statistiques': typeof EntrepriseStatistiquesRoute
  '/admin/': typeof AdminIndexRoute
  '/entreprise/': typeof EntrepriseIndexRoute
  '/admin/commandes/$id': typeof AdminCommandesIdRoute
  '/admin/marchands/$id': typeof AdminMarchandsIdRoute
  '/admin/transporteurs/$id': typeof AdminTransporteursIdRoute
  '/admin/transporteurs/nouveau': typeof AdminTransporteursNouveauRoute
  '/entreprise/livreurs/nouveau': typeof EntrepriseLivreursNouveauRoute
  '/admin/commandes/': typeof AdminCommandesIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/marchands/': typeof AdminMarchandsIndexRoute
  '/admin/transporteurs/': typeof AdminTransporteursIndexRoute
  '/entreprise/livraisons/': typeof EntrepriseLivraisonsIndexRoute
  '/entreprise/livreurs/': typeof EntrepriseLivreursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entreprise'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/entreprise/mot-de-passe'
    | '/entreprise/operations'
    | '/entreprise/profil'
    | '/entreprise/retards'
    | '/entreprise/statistiques'
    | '/admin/'
    | '/entreprise/'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/transporteurs/nouveau'
    | '/entreprise/livreurs/nouveau'
    | '/admin/commandes/'
    | '/admin/comptes/'
    | '/admin/marchands/'
    | '/admin/transporteurs/'
    | '/entreprise/livraisons/'
    | '/entreprise/livreurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/entreprise/mot-de-passe'
    | '/entreprise/operations'
    | '/entreprise/profil'
    | '/entreprise/retards'
    | '/entreprise/statistiques'
    | '/admin'
    | '/entreprise'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/transporteurs/nouveau'
    | '/entreprise/livreurs/nouveau'
    | '/admin/commandes'
    | '/admin/comptes'
    | '/admin/marchands'
    | '/admin/transporteurs'
    | '/entreprise/livraisons'
    | '/entreprise/livreurs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entreprise'
    | '/login'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/livraisons'
    | '/admin/parametres'
    | '/entreprise/mot-de-passe'
    | '/entreprise/operations'
    | '/entreprise/profil'
    | '/entreprise/retards'
    | '/entreprise/statistiques'
    | '/admin/'
    | '/entreprise/'
    | '/admin/commandes/$id'
    | '/admin/marchands/$id'
    | '/admin/transporteurs/$id'
    | '/admin/transporteurs/nouveau'
    | '/entreprise/livreurs/nouveau'
    | '/admin/commandes/'
    | '/admin/comptes/'
    | '/admin/marchands/'
    | '/admin/transporteurs/'
    | '/entreprise/livraisons/'
    | '/entreprise/livreurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EntrepriseRoute: typeof EntrepriseRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise': {
      id: '/entreprise'
      path: '/entreprise'
      fullPath: '/entreprise'
      preLoaderRoute: typeof EntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprise/': {
      id: '/entreprise/'
      path: '/'
      fullPath: '/entreprise/'
      preLoaderRoute: typeof EntrepriseIndexRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entreprise/statistiques': {
      id: '/entreprise/statistiques'
      path: '/statistiques'
      fullPath: '/entreprise/statistiques'
      preLoaderRoute: typeof EntrepriseStatistiquesRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/entreprise/retards': {
      id: '/entreprise/retards'
      path: '/retards'
      fullPath: '/entreprise/retards'
      preLoaderRoute: typeof EntrepriseRetardsRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/entreprise/profil': {
      id: '/entreprise/profil'
      path: '/profil'
      fullPath: '/entreprise/profil'
      preLoaderRoute: typeof EntrepriseProfilRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/entreprise/operations': {
      id: '/entreprise/operations'
      path: '/operations'
      fullPath: '/entreprise/operations'
      preLoaderRoute: typeof EntrepriseOperationsRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/entreprise/mot-de-passe': {
      id: '/entreprise/mot-de-passe'
      path: '/mot-de-passe'
      fullPath: '/entreprise/mot-de-passe'
      preLoaderRoute: typeof EntrepriseMotDePasseRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/livraisons': {
      id: '/admin/livraisons'
      path: '/livraisons'
      fullPath: '/admin/livraisons'
      preLoaderRoute: typeof AdminLivraisonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entreprise/livreurs/': {
      id: '/entreprise/livreurs/'
      path: '/livreurs'
      fullPath: '/entreprise/livreurs/'
      preLoaderRoute: typeof EntrepriseLivreursIndexRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/entreprise/livraisons/': {
      id: '/entreprise/livraisons/'
      path: '/livraisons'
      fullPath: '/entreprise/livraisons/'
      preLoaderRoute: typeof EntrepriseLivraisonsIndexRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/admin/transporteurs/': {
      id: '/admin/transporteurs/'
      path: '/transporteurs'
      fullPath: '/admin/transporteurs/'
      preLoaderRoute: typeof AdminTransporteursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marchands/': {
      id: '/admin/marchands/'
      path: '/marchands'
      fullPath: '/admin/marchands/'
      preLoaderRoute: typeof AdminMarchandsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comptes/': {
      id: '/admin/comptes/'
      path: '/comptes'
      fullPath: '/admin/comptes/'
      preLoaderRoute: typeof AdminComptesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes/': {
      id: '/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AdminCommandesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entreprise/livreurs/nouveau': {
      id: '/entreprise/livreurs/nouveau'
      path: '/livreurs/nouveau'
      fullPath: '/entreprise/livreurs/nouveau'
      preLoaderRoute: typeof EntrepriseLivreursNouveauRouteImport
      parentRoute: typeof EntrepriseRoute
    }
    '/admin/transporteurs/nouveau': {
      id: '/admin/transporteurs/nouveau'
      path: '/transporteurs/nouveau'
      fullPath: '/admin/transporteurs/nouveau'
      preLoaderRoute: typeof AdminTransporteursNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transporteurs/$id': {
      id: '/admin/transporteurs/$id'
      path: '/transporteurs/$id'
      fullPath: '/admin/transporteurs/$id'
      preLoaderRoute: typeof AdminTransporteursIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marchands/$id': {
      id: '/admin/marchands/$id'
      path: '/marchands/$id'
      fullPath: '/admin/marchands/$id'
      preLoaderRoute: typeof AdminMarchandsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes/$id': {
      id: '/admin/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/admin/commandes/$id'
      preLoaderRoute: typeof AdminCommandesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminLivraisonsRoute: typeof AdminLivraisonsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCommandesIdRoute: typeof AdminCommandesIdRoute
  AdminMarchandsIdRoute: typeof AdminMarchandsIdRoute
  AdminTransporteursIdRoute: typeof AdminTransporteursIdRoute
  AdminTransporteursNouveauRoute: typeof AdminTransporteursNouveauRoute
  AdminCommandesIndexRoute: typeof AdminCommandesIndexRoute
  AdminComptesIndexRoute: typeof AdminComptesIndexRoute
  AdminMarchandsIndexRoute: typeof AdminMarchandsIndexRoute
  AdminTransporteursIndexRoute: typeof AdminTransporteursIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminLivraisonsRoute: AdminLivraisonsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCommandesIdRoute: AdminCommandesIdRoute,
  AdminMarchandsIdRoute: AdminMarchandsIdRoute,
  AdminTransporteursIdRoute: AdminTransporteursIdRoute,
  AdminTransporteursNouveauRoute: AdminTransporteursNouveauRoute,
  AdminCommandesIndexRoute: AdminCommandesIndexRoute,
  AdminComptesIndexRoute: AdminComptesIndexRoute,
  AdminMarchandsIndexRoute: AdminMarchandsIndexRoute,
  AdminTransporteursIndexRoute: AdminTransporteursIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EntrepriseRouteChildren {
  EntrepriseMotDePasseRoute: typeof EntrepriseMotDePasseRoute
  EntrepriseOperationsRoute: typeof EntrepriseOperationsRoute
  EntrepriseProfilRoute: typeof EntrepriseProfilRoute
  EntrepriseRetardsRoute: typeof EntrepriseRetardsRoute
  EntrepriseStatistiquesRoute: typeof EntrepriseStatistiquesRoute
  EntrepriseIndexRoute: typeof EntrepriseIndexRoute
  EntrepriseLivreursNouveauRoute: typeof EntrepriseLivreursNouveauRoute
  EntrepriseLivraisonsIndexRoute: typeof EntrepriseLivraisonsIndexRoute
  EntrepriseLivreursIndexRoute: typeof EntrepriseLivreursIndexRoute
}

const EntrepriseRouteChildren: EntrepriseRouteChildren = {
  EntrepriseMotDePasseRoute: EntrepriseMotDePasseRoute,
  EntrepriseOperationsRoute: EntrepriseOperationsRoute,
  EntrepriseProfilRoute: EntrepriseProfilRoute,
  EntrepriseRetardsRoute: EntrepriseRetardsRoute,
  EntrepriseStatistiquesRoute: EntrepriseStatistiquesRoute,
  EntrepriseIndexRoute: EntrepriseIndexRoute,
  EntrepriseLivreursNouveauRoute: EntrepriseLivreursNouveauRoute,
  EntrepriseLivraisonsIndexRoute: EntrepriseLivraisonsIndexRoute,
  EntrepriseLivreursIndexRoute: EntrepriseLivreursIndexRoute,
}

const EntrepriseRouteWithChildren = EntrepriseRoute._addFileChildren(
  EntrepriseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EntrepriseRoute: EntrepriseRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
